# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   test:
     if: ${{ github.head_ref == 'test' }}
     runs-on: ubuntu-latest
     steps:
       - name: dupa
         run: |
           echo $GITHUB_BASE_REF
   build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: env
      run: |
        env
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: http://www.rychel.dev:8080
        user: "Zbychu"
        token: ${{ secrets.TOKEN }}
        job: "Simple_api_test"
